GustaffWeb/Controllers/DespesasController.cs
using GustaffWeb.Data;
using GustaffWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Security.Claims;

namespace GustaffWeb.Controllers
{
    [Authorize]
    public class DespesasController : Controller
    {
        private readonly Context db;
        private readonly UserManager<IdentityUser> _userManager;
        private string userId;

        public DespesasController(Context db, UserManager<IdentityUser> userManager)
        {
            this.db = db;
            this._userManager = userManager;
        }


        public IActionResult Index(int? mes)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var despesas = db.Despesas.Where(s => s.UserId == userId).ToList();

            int mesSelecionado = mes.HasValue ? mes.Value : DateTime.Now.Month;
            ViewBag.MesSelecionado = mesSelecionado;

            if (mes.HasValue)
            {
                despesas = despesas.Where(d => d.Vencimento.Month == mes.Value).ToList(); 
            }
            else
            {
                despesas = despesas.Where(d => d.Vencimento.Month == DateTime.Now.Month).ToList();
            }

            // Calcular totais
            var totalDespesasPagas = despesas.Where(d => d.Pago).Sum(d => d.Preco);
            var totalDespesasNaoPagas = despesas.Where(d => !d.Pago).Sum(d => d.Preco);

            // Passar totais para a view
            ViewBag.TotalDespesasPagas = totalDespesasPagas;
            ViewBag.TotalDespesasNaoPagas = totalDespesasNaoPagas;

            return View(despesas);
        }

        [HttpPost]
        public async Task<IActionResult> AdicionarGastos(DespesasModel model)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                if (userId != null)
                {
                    model.UserId = userId;

                    // Salvando a despesa atual
                    db.Despesas.Add(model);

                    // Verificando se é uma despesa fixa e número de parcelas foi definido
                    if (model.Fixo && model.NumeroParcelas > 1)
                    {
                        for (int i = 1; i < model.NumeroParcelas; i++)
                        {
                            // Criar uma nova instância de despesa para cada mês adicional
                            var novaDespesa = new DespesasModel
                            {
                                Titulo = model.Titulo,
                                Preco = model.Preco,
                                Fixo = model.Fixo,
                                Pago = false,
                                NumeroParcelas = model.NumeroParcelas,
                                Data = DateTime.Now,
                                Vencimento = model.Vencimento.AddMonths(i),
                                UserId = userId
                            };

                            db.Despesas.Add(novaDespesa);
                        }
                    }

                    await db.SaveChangesAsync();

                    TempData["mensagem"] = MensagemModel.Serializar("Nova despesa adicionada com sucesso!");

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Usuário não encontrado.");
                    Debug.WriteLine("Erro: Usuário não encontrado.");
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Erro ao salvar as alterações: {ex}");
                TempData["mensagem"] = MensagemModel.Serializar("Houve um erro: " + ex.Message, TipoMensagem.Erro);
                return RedirectToAction("Index");
            }

            TempData["mensagem"] = MensagemModel.Serializar("Houve um erro", TipoMensagem.Erro);
            return RedirectToAction("Index");
        }

        //Ver detalher da despesa
        public IActionResult Ver(int id)
        {
            var Des = db.Despesas.Where(g => g.DespesasId == id).FirstOrDefault();
            if (Des == null)
            {
                return NotFound();
            }

            return View(Des);
        }

        [HttpPost]
        public IActionResult AtualizarStatus(int id)
        {
            var despesa = db.Despesas.Where(g => g.DespesasId == id).FirstOrDefault();
            if (despesa == null)
            {
                return NotFound();
            }

            despesa.Pago = true;
            db.SaveChanges();

            TempData["mensagem"] = MensagemModel.Serializar("Divida paga!");
            return RedirectToAction("Index", new { id = despesa.DespesasId });
        }

        [HttpPost]
        public IActionResult Apagar(int id)
        {
            db.Despesas.Remove(db.Despesas.Where(g => g.DespesasId == id).FirstOrDefault());
            db.SaveChanges();

            TempData["mensagem"] = MensagemModel.Serializar("O registro foi apagado!", TipoMensagem.Erro);

            return RedirectToAction("Index");
        }

        //Graficos
        public IActionResult Graficos()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId == null)
            {
                TempData["mensagem"] = "Usuário não encontrado.";
                return RedirectToAction("Index");
            }

            // Filtrando somente despesas pagas e agrupando por mês
            var dadosGraficos = db.Despesas
                                  .Where(d => d.UserId == userId && d.Pago == true) // Apenas despesas pagas
                                  .GroupBy(d => d.Vencimento.Month)
                                  .Select(g => new
                                  {
                                      Mes = g.Key,
                                      Total = g.Sum(d => d.Preco)
                                  }).OrderBy(d => d.Mes) // Ordenando pelos meses
                                  .ToList();

            ViewBag.Meses = dadosGraficos.Select(d => System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(d.Mes)).ToList();
            ViewBag.Totais = dadosGraficos.Select(d => d.Total).ToList();

            return View();
        }
    }
}

GustaffWeb/Controllers/InicioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GustaffWeb.Controllers
{
    [Authorize]
    public class InicioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GustaffWeb/Controllers/SitesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GustaffWeb.Controllers
{
    public class SitesController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
    }
}

GustaffWeb/Views/Shared/_AdicionarGastos.cshtml
@model GustaffWeb.Models.DespesasModel

<form asp-action="AdicionarGastos" method="post" onsubmit="prepareForSubmit()">
    <div class="form-group">
        <label asp-for="Titulo"></label><br />
        <input class="form-control" asp-for="Titulo" />
        <span asp-validation-for="Titulo"></span>
    </div><br />

    <div class="form-group">
        <label asp-for="@Model.Preco">Preço pago</label>
        <input asp-for="@Model.Preco" class="form-control" id="preco" placeholder="R$" value="">
        <span asp-validation-for="@Model.Preco"></span>
    </div> <br />

    <div class="form-group">
        <label asp-for="Vencimento">Data de vencimento</label><br />
        <input class="form-control" asp-for="Vencimento" type="date" />
        <span asp-validation-for="Vencimento"></span>
    </div><br />

    <div class="form-group">
        <label>Despesa fixa</label><br />
        <input type="radio" asp-for="Fixo" name="Fixo" value="true" id="fixoSim" onchange="toggleFields()"> <label for="fixoSim">SIM</label>
        <input type="radio" asp-for="Fixo" name="Fixo" value="false" id="fixoNao" onchange="toggleFields()" checked> <label for="fixoNao">NÃO</label>
        <span asp-validation-for="Fixo"></span>
    </div><br />

    <div class="form-group" id="parcelasField" style="display: none;">
        <label asp-for="NumeroParcelas">Número de parcelas</label><br />
        <input class="form-control" asp-for="NumeroParcelas" />
        <span asp-validation-for="NumeroParcelas"></span>
    </div><br />

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
</form>

<script>
    function toggleFields() {
        var fixoSim = document.getElementById("fixoSim");
        var parcelasField = document.getElementById("parcelasField");

        if (fixoSim.checked) {
            parcelasField.style.display = "block";
        } else {
            parcelasField.style.display = "none";
        }
    }

    // Chama a função ao carregar a página para assegurar que os campos sejam definidos corretamente
    document.addEventListener('DOMContentLoaded', function() {
        toggleFields();
    });

    // Formata o campo de preço para o Real Brasileiro
    document.addEventListener('DOMContentLoaded', function () {
        var precoInput = document.getElementById('preco');
        precoInput.addEventListener('input', function (e) {
            var value = e.target.value;
            value = value.replace(/\D/g, ''); // Remove tudo que não é dígito
            value = value.replace(/(\d)(\d{2})$/, '$1,$2'); // Coloca a vírgula antes dos últimos 2 dígitos
            value = value.replace(/(?=(\d{3})+(\D))\B/g, '.'); // Coloca o ponto a cada 3 dígitos
            e.target.value = value;
        });
    });
</script>

GustaffWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GustaffWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GustaffWeb.styles.css" asp-append-version="true" />
</head>
<body>

    <header id="header">
       
        <a id="logo" asp-controller="Home" asp-action="index"> <img src="~/imagens/logoCapa.png" alt="logo" /> </a>

        <nav id="nav">

            <button id="btn-mobile">
                <span id="hamburger"></span>
            </button>

            <ul id="menu">
                <li>
                    <div class="dropdown show">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Conta
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" asp-controller="Account" asp-action="Register">Criar conta</a>
                            <a class="dropdown-item" asp-controller="Account" asp-action="EsqueciSenha">Recuperar conta</a>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Register">Porque ter uma conta</a>
                        </div>
                    </div>
                </li>
                <li><a asp-controller="Sites" asp-action="Index">Sites</a></li>
                <li><a asp-controller="Home" asp-action="Index" onclick="aviso()">Videos</a></li>
                <li><a asp-controller="Home" asp-action="Contatos" >Contatos</a></li>
            </ul> 

        </nav>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

GustaffWeb/Views/Shared/_LayoutApp.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GustaffWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/siteDois.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GustaffWeb.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <nav>
        <div class="logo"> Despesas </div>

        <div class="menu-btn">
            <i class="fa fa-bars fa-2x" onclick="menuShow()"></i>
        </div>

        <ul>
            <li> <a asp-controller="Inicio" asp-action="Index" class="active">Inicio</a> </li>
            <li> <a asp-controller="Sites" asp-action="Index">Apps</a> </li>
            <li> <a asp-action="Contatos" asp-controller="Home">Contatos</a> </li>
            <li> <a href="#">Ajuda</a> </li>
            <li> <a href="#"> Sobre</a> </li>
        </ul>
    </nav>
    <br />
    <br />
    <br />
    <br />

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <br />
    <br />
    <br />
    <br />
    <footer>
        <div class="aMenu">
            <div>
                <a class="btn btn-light" asp-controller="Despesas" asp-action="Index">
                    <img src="~/icones/lista.png" alt="Lista" />
                </a>
            </div>
            <div>
                <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModalCenter">
                    <img src="~/icones/add.png" alt="Adicionar" />
                </button>
            </div>
            <div>
                <a class="btn btn-light" asp-controller="Despesas" asp-action="Graficos">
                    <img src="~/icones/gra.png" alt="Gráfico" />
                </a>
            </div>
            <div>
                <a class="btn btn-light" asp-controller="Despesas" asp-action="Index">
                    <img src="~/icones/info.png" alt="Lista" />
                </a>
            </div>
        </div>
    </footer>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true"> 
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Adicionar Despesa</h5>
                </div>
                <div class="modal-body">
                    @await Html.PartialAsync("_AdicionarGastos", new GustaffWeb.Models.DespesasModel())
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/app.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

GustaffWeb/Views/Shared/_LayoutDois.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GustaffWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GustaffWeb.styles.css" asp-append-version="true" />
</head>
<body>

    <header id="header">

        <a id="logo" asp-controller="Inicio" asp-action="Index"> <img src="~/imagens/logoCapa.png" alt="logo" /> </a>

        <nav id="nav">

            <button id="btn-mobile">
                <span id="hamburger"></span>
            </button>

            <ul id="menu">
                <li>
                    <div class="dropdown show">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Olá, @User.Identity.Name
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="#" onclick="aviso()">Mudar senha</a>
                            <a class="dropdown-item" href="#" onclick="aviso()">Meu perfil</a>
                            <a class="dropdown-item" href="#" onclick="aviso()">Ajudar site</a>

                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <button type="submit" class="dropdown-item" asp-controller="Account" asp-action="Logout">SAIR</button>
                            </form>

                        </div>
                    </div>
                </li>
                <li><a asp-controller="Sites" asp-action="Index">Sites</a></li>
                <li><a asp-controller="Inicio" asp-action="Index" onclick="aviso()">Videos</a></li>
                <li><a asp-controller="Home" asp-action="Contatos">Contatos</a></li>
            </ul>

        </nav>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

GustaffWeb/Views/Shared/_Mensagem.cshtml
@model GustaffWeb.Models.MensagemModel
@{
    if (TempData.ContainsKey("mensagem"))
    {
        var mensagem = MensagemModel.Desserializar(TempData["mensagem"].ToString());
        <script>
            setTimeout(function() {
                var alert = document.querySelector('.alert');
                if (alert) {
                    alert.style.transition = 'opacity 0.5s';
                    alert.style.opacity = '0';
                    setTimeout(function() {
                        alert.remove();
                    }, 500);
                }
            }, 10000); // 10 segundos
        </script>

        if (mensagem.Tipo == TipoMensagem.Erro)
        {
            <div class="alert alert-danger mt-3 alert-dismissible fade show" role="alert">
                @mensagem.Texto
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        }
        else
        {
            <div class="alert alert-success mt-3 alert-dismissible fade show" role="alert">
                @mensagem.Texto
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        }
    }
}